updated error handling & variable naming -- classip

diff --git a/classip b/classip
--- a/classip
+++ b/classip
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 #
 # classip :: ipv4 class information
-# requires: bash 4.0+
+# requires: bash 3.2+
 
 trap 'echo -e "\nSIGINT Received... exiting"; exit 130' SIGINT
 
@@ -10,38 +10,47 @@ err() {
   echo "[${0##*/}] error: $*" >&2
 }
 
+warn() {
+  # send warnings to standard error
+  echo "[${0##*/}] warning: $*" >&2
+}
+
 show_help() {
   # help option text
-  echo "Usage: ${0##*/} [-c -r -s] [<ip address>] ..."
+  echo "Usage: ${0##*/} [OPTION]... [IP ADDRESS]..."
   echo "Options:"
   echo "  -h, --help    Show this help menu"
   echo "  -c            Show all IP class ranges"
   echo "  -r            Show all private IP ranges"
   echo "  -s            Show all special IP ranges"
-  echo ""
 }
 
-parse_options() {
+_parse_options() {
   # parse arguments and assign variables, arrays
 
   # check for long "--help"
   if [[ "$1" == "--help" ]]; then
     show_help
-    exit 0
+    showed_help="1"
+    return 0
   fi
 
-  # $class $private $special must be already delcared in parent function
-  local opt
+  # showed_help, class, private, special - must be declared in main
+  local opt=""
   while getopts ":hcrs" opt; do
     case "$opt" in
-      h) show_help; exit 0 ;;
+      h)
+        show_help
+        showed_help="1"
+        return 0
+        ;;
       c) class="c" ;;
       r) private="r" ;;
       s) special="s" ;;
       \?)
         err "Invalid option: -$OPTARG"
         show_help
-        exit 1
+        return 1
         ;;
     esac
   done
@@ -49,8 +58,6 @@ parse_options() {
 
 print_class_info() {
   # message echo'd to the terminal to see classes and ip ranges
-  #
-
   echo "           All IP Ranges"
   echo "------------------------------------"
   echo " Class   Range"
@@ -65,8 +72,6 @@ print_class_info() {
 
 print_private_info() {
   # message echo'd to the terminal to see private ip ranges
-  #
-
   echo "          Private IP Ranges"
   echo "--------------------------------------"
   echo " Class   Range"
@@ -81,8 +86,6 @@ print_private_info() {
 
 print_special_info() {
   # message echo'd to the terminal to see special ip information
-  #
-
   echo "            Special IPv4 Addresses"
   echo "---------------------------------------------------"
   echo " Type                 Range"
@@ -98,32 +101,47 @@ option_printer() {
   # print output based on arguments/options
   #
   # ARG $1: options string
+  # RET: none, runs print functions based on $1
 
   [[ "$1" =~ c|r|s ]] && echo ""
   [[ "$1" =~ c ]] && print_class_info
   [[ "$1" =~ r ]] && print_private_info
   [[ "$1" =~ s ]] && print_special_info
+
+  # return passed if no options were requested
+  return 0
 }
 
 validate_ip_address() {
   # assess if a given ip address is a valid ipv4 address
   #
   # ARG $1: ip address
+  # RET: 1 if failed
 
-  [[ "$1" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]] || return 1
+  if ! [[ "$1" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; then
+    warn "\"${1}\" is not a valid IP address!"
+    return 1
+  fi
 
-  local -a ip_arr
+  local -a ip_array=()
 
-  # convert ip address to array
-  IFS='.' read -r -a ip_arr <<< "$1"
+  # convert ip address to an array
+  IFS='.' read -r -a ip_array <<< "$1"
 
-  local i
-  for i in "${ip_arr[@]}"; do
-    [[ "$i" != "0" && "$i" =~ ^0 ]] && return 1
-    ((i < 0 || i > 255)) && return 1
+  local octet_value=""
+  for octet_value in "${ip_array[@]}"; do
+    if [[ "$octet_value" != "0" && "$octet_value" =~ ^0 ]]; then
+      warn "\"${1}\" is not a valid IP address!"
+      return 1
+    fi
+
+    if (( octet_value < 0 || octet_value > 255 )); then
+      warn "\"${1}\" is not a valid IP address!"
+      return 1
+    fi
   done
 
-  # return
+  # return - input validation passed
   return 0
 }
 
@@ -133,18 +151,17 @@ get_ip_class() {
   # ARG $1: ip address
   # RET: ip class
 
-  local ipaddr
-  ipaddr="${1%%\.*}"
+  local ip_first_octet="${1%%\.*}"
 
-  if (( ipaddr >= 0 && ipaddr <= 127 )); then
+  if (( ip_first_octet >= 0 && ip_first_octet <= 127 )); then
     echo -n "A"
-  elif (( ipaddr >= 128 && ipaddr <= 191 )); then
+  elif (( ip_first_octet >= 128 && ip_first_octet <= 191 )); then
     echo -n "B"
-  elif (( ipaddr >= 192 && ipaddr <= 223 )); then
+  elif (( ip_first_octet >= 192 && ip_first_octet <= 223 )); then
     echo -n "C"
-  elif (( ipaddr >= 224 && ipaddr <= 239 )); then
+  elif (( ip_first_octet >= 224 && ip_first_octet <= 239 )); then
     echo -n "D"
-  elif (( ipaddr >= 240 && ipaddr <= 255 )); then
+  elif (( ip_first_octet >= 240 && ip_first_octet <= 255 )); then
     echo -n "E"
   fi
 }
@@ -155,18 +172,18 @@ get_ip_pripub() {
   # ARG $1: ip address
   # RET: private or public
 
-  local -a octet_arr
-  IFS='.' read -r -a octet_arr <<< "$1"
+  local -a ip_array=()
+  IFS='.' read -r -a ip_array <<< "$1"
 
-  if (( octet_arr[0] == 10 )); then
+  if (( ip_array[0] == 10 )); then
     echo -n "private"
-  elif (( octet_arr[0] == 169 && octet_arr[1] == 254 )); then
+  elif (( ip_array[0] == 169 && ip_array[1] == 254 )); then
     echo -n "private"
-  elif (( octet_arr[0] == 172 && octet_arr[1] >= 16 && octet_arr[1] <= 31 )); then
+  elif (( ip_array[0] == 172 && ip_array[1] >= 16 && ip_array[1] <= 31 )); then
     echo -n "private"
-  elif (( octet_arr[0] == 192 && octet_arr[1] == 168 )); then
+  elif (( ip_array[0] == 192 && ip_array[1] == 168 )); then
     echo -n "private"
-  elif (( octet_arr[0] >= 224 && octet_arr[0] <= 255 )); then
+  elif (( ip_array[0] >= 224 && ip_array[0] <= 255 )); then
     echo -n "private"
   else
     echo -n "public"
@@ -180,44 +197,48 @@ get_ip_special() {
   # ARG $1: ip address
   # RET: special ip type, or nothing
 
-  local -a octet_arr
-  IFS='.' read -r -a octet_arr <<< "$1"
+  local -a ip_array=()
+  IFS='.' read -r -a ip_array <<< "$1"
 
-  if (( octet_arr[0] == 127 )); then
+  if (( ip_array[0] == 127 )); then
     echo -n "loopback"
-  elif (( octet_arr[0] == 169 && octet_arr[1] == 254 )); then
+  elif (( ip_array[0] == 169 && ip_array[1] == 254 )); then
     echo -n "link-local"
-  elif (( octet_arr[0] >= 224 && octet_arr[0] <= 239 )); then
+  elif (( ip_array[0] >= 224 && ip_array[0] <= 239 )); then
     echo -n "multicast"
-  elif (( octet_arr[0] >= 240 && octet_arr[0] <= 255 )); then
+  elif (( ip_array[0] >= 240 && ip_array[0] <= 255 )); then
     echo -n "reserved"
   fi
 }
 
 main() {
-  # check for at least one argument before getopts and shift
-  if [[ $# -le 0 ]]; then
+  set -eu
+
+  # define variables that can be assigned in _parse_options
+  local showed_help="" class="" private="" special=""
+  if [[ $# -gt 0 ]]; then
+    _parse_options "$@"
+    [[ -n "$showed_help" ]] && exit 0
+  else
     err "One argument required: <option> and/or <ip address>"
     echo "---"
     show_help
     exit 1
   fi
-  local class private special
-  parse_options "$@"
   shift $((OPTIND - 1)) # shift $@ past optional flags
+
   option_printer "${class}${private}${special}"
 
-  local _ip ip_class ip_pripub ip_special
-  for _ip in "$@"; do
-    if ! validate_ip_address "$_ip"; then
-      err "\"${1}\" : Invalid IP address"
-      continue
-    fi
-    ip_class=$(get_ip_class "$_ip")
-    ip_pripub=$(get_ip_pripub "$_ip")
-    ip_special=$(get_ip_special "$_ip")
+  local ip_address="" ip_class="" ip_pripub="" ip_special=""
+  # iterate through ip addresses and gather and print information
+  for ip_address in "$@"; do
+    validate_ip_address "$ip_address" || continue
 
-    echo "$_ip : $ip_class $ip_pripub $ip_special"
+    ip_class=$(get_ip_class "$ip_address")
+    ip_pripub=$(get_ip_pripub "$ip_address")
+    ip_special=$(get_ip_special "$ip_address")
+
+    echo "$ip_address : $ip_class $ip_pripub $ip_special"
   done
 }
 
